### ISSUE TITLE
Space char not properly escaped in urlEncodedStringWithEncoding extension

### ISSUE THREAD

**Issue by dscottbuch** [OAuthSwift/OAuthSwift#164] opened 2015-12-23 18:46 UTC
I didn't find this elsewhere in the tickets.  I found that in
```swift
    func urlEncodedStringWithEncoding(encoding: NSStringEncoding) -> String {
        let originalString: NSString = self
        let customAllowedSet =  NSCharacterSet(charactersInString:":/?&=;+!@#$()',*=\"#%/<>?@\\^`{|} ").invertedSet
        let escapedString = originalString.stringByAddingPercentEncodingWithAllowedCharacters(customAllowedSet)
        return escapedString! as String
    }
```
the set of dis-allowed characters in the NSCharacterSet call did not include a space ' '.  This would cause the forces unwrapped optional at the end of the URLByAppendingQueryString call to fail every time if the query being attempted contained a space.  Added a ' ' to the list of characters fixes this.

Scott

**Comment by phimage** [comment] 2015-12-23 18:49
it's a duplicate of #156 
the dev who open it also close it after creating the PR #157

**Closed by phimage** 2015-12-23 18:49 UTC
Labels: duplicate
