### ISSUE TITLE
mac catalyst _OBJC_CLASS_$_SFAuthenticationSession compilation error

### ISSUE THREAD

**Issue by djk12587** [OAuthSwift/OAuthSwift#555] opened 2019-11-01 03:36 UTC
### Description:
Try building a mac catalyst app with OAtuhSwift added as a Swift Package. You will get a compilation error complaining about SFAuthenticationSession.

### OAuth Version:
- [ ] Version 1
- [ ] Version 2

### OS (Please fill the version) :
- [ ] iOS :
- [ ] OSX :
- [ ] TVOS :
- [ ] WatchOS  :
- [x] mac catalyst  :

### Installation method:
- [ ] Carthage
- [ ] CocoaPods
- [x] Swift Package Manager
- [ ] Manually

### Library version:
- [x] head
- [ ] v2.1.0
- [ ] v2.0.0
- [ ] v1.4.1
- [ ] v1.2 (Swift 4.0)
- [ ] other: (Please fill in the version you are using.)

### Xcode version:
- [x] 11.x (Swift 5.1)
- [ ] 10.x (Swift 5.0)
- [ ] 10.x (Swift 4.1)
- [ ] 9.3 (Swift 4.1)
- [ ] 9.0 (Swift 4.0)
- [ ] other: (Please fill in the version you are using.)

- [ ] objective c

**Comment by phimage** [comment] 2019-11-01 14:50
duplicate of #547

**Closed by phimage** 2019-11-01 14:50 UTC
