### ISSUE TITLE
Incorrect signature when parameter includes a [ or ]

### ISSUE THREAD

**Issue by obuseme** [OAuthSwift/OAuthSwift#174] opened 2016-01-18 20:31 UTC
Using the AWeber public API (https://labs.aweber.com/docs) I discovered that when passing parameters with OAuthSwift requests that include braces, [ or ], they aren't actually encoded, and thus the signature isn't properly created.  When the server attempts to verify the signature, it does so based on encoded values for the braces, and thus does not match what the client provides.  I created #173 to fix this.  Let me know what you think.

**Comment by phimage** [comment] 2016-01-18 20:46
#173 exact duplicate of #168
#169 also introduce bracket (but do more change)

one of this PR will fix this bug

**Comment by obuseme** [comment] 2016-01-18 20:59
Oops, my bad, totally missed #168.  Doesn't matter to me which one merges, as long as one does.  Should I close mine?  Need this change available via CocoaPods ASAP.  Thanks

I'm not seeing anything related to braces in #169 ?

**Comment by phimage** [comment] 2016-01-18 21:01
#165 If fix my comment
I already close your PR but keep the issue open

**Comment by obuseme** [comment] 2016-01-18 21:09
Ok, thanks

**Comment by danielbmarques** [comment] 2016-03-03 23:12
No news on merging this? I'm having trouble with the brackets as well.

**Comment by phimage** [comment] 2016-03-05 10:44
The reason why I have not yet merged are
- 3 fix about signature (2 PR and one issue where you commented)
- no enough unit tests (to prevent regression on signature) so I am little scared :p (if one oauth provider work differently from others.. for instance)

Any help will be welcomed

**Comment by phimage** [comment] 2016-03-09 09:07
PR #201 must fix this one

**Closed by phimage** 2016-03-09 09:07 UTC
Labels: bug
